"""add pending_ratings table

Revision ID: 37a963ac4704
Revises: a86a43e98017
Create Date: 2026-03-11 23:46:43.038828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a963ac4704'
down_revision: Union[str, None] = 'a86a43e98017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('title_name', sa.String(length=500), nullable=False),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('rated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_ratings_title_id'), 'pending_ratings', ['title_id'], unique=False)
    op.create_index(op.f('ix_pending_ratings_user_id'), 'pending_ratings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_ratings_user_id'), table_name='pending_ratings')
    op.drop_index(op.f('ix_pending_ratings_title_id'), table_name='pending_ratings')
    op.drop_table('pending_ratings')
    # ### end Alembic commands ###
